# Generated by Django 4.0.3 on 2022-04-19 09:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0007_remove_costumer_password_remove_costumer_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('identifier', models.SlugField(default=models.CharField(max_length=40))),
                ('discription', ckeditor.fields.RichTextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_used_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(max_length=256, upload_to='service_images')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.services')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.costumer')),
                ('comments_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.services')),
            ],
        ),
    ]
