# Generated by Django 4.0.3 on 2022-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='identifier',
            field=models.SlugField(default=models.CharField(max_length=40), unique=True),
        ),
    ]
