# Generated by Django 4.0.3 on 2022-04-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_comments_content_type_comments_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
