# Generated by Django 4.0.3 on 2022-04-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_comments_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments_count',
            new_name='service_id',
        ),
    ]
