# Generated by Django 4.0.3 on 2022-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_rename_comments_count_comments_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
