# Generated by Django 4.0.3 on 2022-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('create_user_time', models.DateTimeField(verbose_name='time created')),
                ('last_login_time', models.DateTimeField(verbose_name='time logged in last')),
            ],
        ),
    ]
