# Generated by Django 4.0 on 2022-04-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_costumer_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='department',
            new_name='citizen',
        ),
    ]
