# Generated by Django 4.0 on 2022-04-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_rename_department_costumer_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='costumer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='contacts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='costumer',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='costumer',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='costumer',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='citizen',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
