# Generated by Django 4.0.3 on 2022-04-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_costumer_address_costumer_age_costumer_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='username',
        ),
        migrations.AlterField(
            model_name='costumer',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
