# Generated by Django 4.0.3 on 2022-04-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_remove_costumer_password_remove_costumer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='last_name',
        ),
    ]
